model:
  n_layers: 2
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 64
  dropout: 0.5
  input_dropout: 0
  norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  n_heads: 1
  ff: false
  hidden_dim_multiplier: 1
  use_norm: false
  use_residual: false
  input_layer: false
  output_layer: false

dataset:
  feat_norm: true
  cora_split: false
  load_graph: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 500
  weight_decay: 5e-4
  patience: ~
  criterion: ~

# analysis
analysis:
  flag: false
  sweep: false
  sweep_id: yotsugi/gsl-benchmark/zraif59m
  project: gsl
  save_graph: false
  graph_analysis: false
  dir: wandb/gt_cora
  count: 3