model:
  n_layers: 5
  act: gelu # [relu, elu, gelu, leakyrelu]
  n_hidden: 512
  dropout: 0.2
  input_dropout: 0.2
  norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  n_heads: 8
  ff: true
  hidden_dim_multiplier: 1

dataset:
  re_split: true # for cora,citeseer and pubmed
  load_graph:
    flag: false
    loc: results/graph/grcn

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 3e-5
  n_epochs: 1000
  weight_decay: 0

# analysis
analysis:
  flag: true
  project: gsl
  save_graph: false
  dir: gt_hetero
  graph_analysis: true
  group: attn_weights