model:
  n_layers: 2
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 32
  dropout: 0.2
  input_dropout: 0
  norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  n_heads: 8
  ff: false
  hidden_dim_multiplier: 1
  use_norm: false
  use_residual: false
  input_layer: true
  output_layer: false

dataset:
  feat_norm: false
  cora_split: false
  load_graph: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 1000
  weight_decay: 5e-4

# analysis
analysis:
  flag: false
  sweep: false
  sweep_id: yotsugi/gsl-benchmark/jp3rzexi
  project: gsl
  save_graph: false
  graph_analysis: false
  dir: wandb/gt_cora
  count: 500