model:
  type: appnp
  K: 6
  alpha: 0.5
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: F.relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 32
  dropout: 0.2
  input_dropout: 0
  norm: ~
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

training:
  lr: 1e-1
  n_epochs: 100
  weight_decay: 5e-5
  patience: 100
  lr_adj: 1e-3
  inner_steps: 2
  outer_steps: 1
  criterion: either

gsl:
  symmetric: false
  lambda_: 0.001
  alpha: 5e-4
  beta: 1.5
  gamma: 1

dataset:
  feat_norm: false
  cora_split: false
  sparse: true
#  without_structure: i

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  save_graph_path: results/graph