model:
  type: gin
  n_hidden: 256
  n_layers: 3
  mlp_layers: 1 
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  n_hidden: 128
  n_embed: 32
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: 'lambda x: x' # [relu, elu, gelu, leakyrelu, identity]
  dropout: 0
  input_dropout: 0
  norm:
    flag: false
    norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions
  gae: true
  alpha: 0.9
  temperature: 0.6

dataset:
  feat_norm: true
  cora_split: false # for cora,citeseer and pubmed
  sparse: true

training:
  lr: 1e-3
  n_epochs: 200
  weight_decay: 0
  warmup: 0
  patience: 100
  pretrain_ep: 160
  pretrain_nc: 30
  beta: 0.8
  criterion: ~

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  save_graph_path: results/graph