model:
  type: gcn
  n_hidden: 128
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu, identity]
  dropout: 0.5
  input_dropout: 0
  norm:
    flag: false
    norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  n_hidden: 128
  n_embed: 32
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: identity # [relu, elu, gelu, leakyrelu, identity]
  dropout: 0
  input_dropout: 0
  norm:
    flag: false
    norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions
  gae: true
  alpha: 0.43
  temperature: 1.0

dataset:
  feat_norm: false
  cora_split: false # for cora,citeseer and pubmed
  sparse: true
  without_structure: ~

training:
  lr: 1e-2
  n_epochs: 200
  weight_decay: 5e-4
  warmup: 9
  patience: 100
  pretrain_ep: 5
  pretrain_nc: 235
  beta: 2.8
  criterion: ~

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  save_graph_path: results/graph