model:
  seed: 3
  cls_hid_1: 64
  com_lambda_v1: 1
  com_lambda_v2: 0.5
  gen_hid: 32
  lam: 0.9
  alpha: 0.1
  mi_hid_1: 32
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.5
  cls_dropout: 0.5
  ve_dropout: 0.8


training:
  cls_lr: 0.01
  cls_weight_decay: 5e-4
  ve_lr: 0.1
  ve_weight_decay: 0
  mi_lr: 0.01
  mi_weight_decay: 0

  main_epoch: 100
  inner_ne_epoch: 5
  inner_cls_epoch: 1
  inner_mi_epoch: 10
  temp_r: 1e-3

  patience: ~
  criterion: ~


dataset:
  name: cora
  init: True    # True : generate view, False : read view
  feat_norm: True
  cora_split: false
  name_view1: view_adj
  name_view2: view_diff
  #view1_path: # *.npz
  #view2_path: # *.npz
  #view1_indices_path:  #*.pt
  #view2_indices_path:  #*.pt
  diff_alpha: 0.15 #
  knn_k: 3
  view1_indices: 2
  view2_indices: 1
  view1_k: 0     # choose the biggest k values for view1_indices
  view2_k: 40    # if k is 0, all of values will be chosen
  to_sparse: False
  pyg: False
  big: False
  batch: 0
  sparse: true
  without_structure: ~

analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph
