model:
  seed: 7
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  cls_dropout: 0.5
  ve_dropout: 0.2


training:
  cls_lr: 0.01
  cls_weight_decay: 5e-4
  ve_lr: 0.001
  ve_weight_decay: 0
  mi_lr: 0.01
  mi_weight_decay: 0

  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 1e-4

  patience: ~
  criterion: ~


dataset:
  name: citeseer
  init: False    # True : generate view, False : read view
  feat_norm: True
  cora_split: false
  name_view1: view_adj
  name_view2: view_diff
  view1_path: data/CiteSeer/CiteSeer/processed/v1_adj.npz
  view2_path: data/CiteSeer/CiteSeer/processed/v2_diff.npz
  view1_indices_path: data/CiteSeer/CiteSeer/processed/v1_2.pt
  view2_indices_path: data/CiteSeer/CiteSeer/processed/v2_40.pt
  diff_alpha: 0.1 #
  knn_k: 3
  view1_indices: 2
  view2_indices: 1
  view1_k: 0     # choose the biggest k values for view1_indices
  view2_k: 40    # if k is 0, all of values will be chosen
  to_sparse: False
  pyg: False
  big: False
  batch: 0
  sparse: true

analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph
