model:
  name: linkx
  n_layers: 2
  n_hidden: 64

training:
  n_epochs: 100
  lr: 0.01
  weight_decay: 0

dataset:
  feat_norm: true
  cora_split: false
  normalize: true
  add_loop: true

analysis:
  flag: false