model:
  name: link

training:
  n_epochs: 100
  lr: 0.01
  weight_decay: 0.1

dataset:
  feat_norm: true
  cora_split: false
  normalize: false
  add_loop: false
  sparse: true


analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: true
  load_graph_path: results/graph/sublime