model:
  name: link

training:
  n_epochs: 100
  lr: 0.1
  weight_decay: 1e-3

dataset:
  feat_norm: true
  cora_split: false
  normalize: true
  add_loop: true
  sparse: true


analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: true
  load_graph_path: results/graph/idgl