model:
  type: gin
  n_hidden: 256
  n_layers: 4
  mlp_layers: 1 
  spmm_type: 1 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  model_type: diag
  K: 50
  normalize: true

dataset:
  feat_norm: false
  sparse: true
#  homophily_control: 0.4

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-3
  n_epochs: 300
  weight_decay: 5e-4
  lr_graph: 1e-1
  patience: ~
  criterion: ~

analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph
