model:
  type: gcn
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 32
  dropout: 0.5
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 1 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  model_type: diag
  K: 200
  normalize: true

dataset:
  feat_norm: false
  sparse: true
#  homophily_control: 0.4

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-3
  n_epochs: 300
  weight_decay: 5e-7
  lr_graph: 1e-1
  patience: ~
  criterion: ~

analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph
