re_split: false

lr: 3e-5
n_epochs: 4000
weight_decay: 0
patience: 100

backbone: gcn
enhancedgcn: true
n_hidden: 512
dropout: 0.2
input_dropout: 0.2   # cora:0.8,citeseer:0.0
norm: false
n_layers: 5

symmetric: true
lambda_: 0
alpha: 0
beta: 0
gamma: 0.3
lr_adj: 1e-2
inner_steps: 2
outer_steps: 1
only_gcn: false
eta: 0.5

#lpcls: 5

# below is for saving results
save_graph: false
