training:
  lr: 1e-1
  weight_decay: 5e-6
  max_iter: 10
  max_epochs: 1000
  patience: 100
  smoothness_ratio: 0
  degree_ratio: 0.03
  sparsity_ratio: 0
  criterion: ~

model:
  type: gcn
  n_layers: 3
  n_hidden: 128
  dropout: 0.2
  norm: false
  scalable_run: true
  num_anchors: 700


gsl:
  graph_skip_conn: 0.9
  update_adj_ratio: 0.2
  graph_include_self: false

  graph_learn_epsilon: 0.1
  graph_learn_epsilon2: 0.1
  graph_learn_topk: null
  graph_learn_topk2: null
  graph_learn_num_pers: 8

  feat_adj_dropout: 0
  gl_dropout: 0

  eps_adj: 8e-5
  test_eps_adj: 8e-5

dataset:
  cora_split: false
  feat_norm: false
  sparse: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  save_graph_path: results/graph