model:
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 32
  dropout: 0.5
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 1 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  model_type: diag
  K: 5
  normalize: true

dataset:
  re_split: false # for cora,citeseer and pubmed

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 5e-3
  n_epochs: 300
  weight_decay: 5e-3
  lr_graph: 1e-3

analysis:
  flag: false
  project: gsl
  save_graph: true

# use wandb to tune hyperparams
sweep:
  flag: true
  sweep_config:
    method: grid
    name: grcn
    description: cora
    metric:
      goal: maximize
      name: loss
    parameters:
      batch_size:
        values: [16,32,64]
      lr:
        min: 0.0001
        max: 0.1
      epochs:
        values: [5, 10, 15]
