model:
  n_layers: 2
  n_hidden: 8
  n_heads: 8
  dropout: 0.5

dataset:
  feat_norm: true
  cora_split: false
  load_graph: false
  sparse: true

training:
  lr: 5e-3
  weight_decay: 5e-4
  n_epochs: 200

analysis:
  flag: false
  project: gsl-benchmark
  save_graph: false
  load_graph: false
  load_graph_path: results/graph/stable