model:
  n_hidden: 64
  dropout: 0.5
  K: 10
  alpha: 0.1

training:
  lr: 1e-2
  weight_decay: 5e-4
  n_epochs: 1000

dataset:
  re_split: true
  load_graph:
    flag: false
    loc: [ results/graph/gen_cora_0_0.pth, results/graph/grcn_cora_0_0.pth ]
  normalize: true
  add_loop: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false