model:
  type: gin
  mlp_gin: 1
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 128
  dropout: 0.8
  graph_skip_conn: 0.9
  graph_learn_num_pers: 1
  no_bn: false
  mlp_layers: 2
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

dataset:
  cora_split: false # for cora,citeseer and pubmed
  feat_norm: false
  normalize: true
  add_loop: true
  sparse: true
#  homophily_control: 0.8

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-1
  n_epochs: 300
  weight_decay: 0
  patience: ~
  criterion: metric

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: false
  load_graph_path: results/graph/gen