model:
  n_layers: 2

training:
  n_epochs: 1000
  lr: 0.1
  weight_decay: 0   # 1.3026973714043257e-05, 2.3545587233182368e-05, 7.403929623323868e-05 for cora, citeseer, pubmed

dataset:
  cora_split: false
  feat_norm: false
  normalize: true
  add_loop: true
  sparse: true

analysis:
  flag: false