model:
  n_layers: 2
  act: F.relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 64
  dropout: 0.8
  input_dropout: 0
  norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  n_heads: 4
  ff: false
  hidden_dim_multiplier: 1
  use_norm: false
  use_residual: false
  input_layer: true
  output_layer: true

dataset:
  feat_norm: true
  cora_split: false
  load_graph: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 1000
  weight_decay: 5e-7
  patience: ~
  criterion: ~

# analysis
analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph