training:
  lr: 0.01
  weight_decay: 5e-4
  max_iter: 10
  max_epochs: 1000
  patience: 100
  smoothness_ratio: 0.4
  degree_ratio: 0
  sparsity_ratio: 0.2
  criterion: ~

model:
  n_layers: 2
  n_hidden: 16
  dropout: 0.5
  norm: false
  scalable_run: false
  num_anchors: 300


gsl:
  graph_skip_conn: 0.6
  update_adj_ratio: 0.5
  graph_include_self: false

  graph_learn_epsilon: 0.3
  graph_learn_epsilon2: 0.3
  graph_learn_topk: null
  graph_learn_topk2: null
  graph_learn_num_pers: 1

  feat_adj_dropout: 0
  gl_dropout: 0

  eps_adj: 1e-3
  test_eps_adj: 1e-3

dataset:
  feat_norm: true
  sparse: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false