model:
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 64
  dropout: 0.5
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  k: 3
  se: 2


dataset:
  feat_norm: true
  cora_split: false # for cora,citeseer and pubmed
  sparse: true

training:
  n_iters: 10
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 200
  weight_decay: 5e-4

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: true
  save_graph_path: results/graph
