model:
  type: gcn
sparse: true
epochs_cls: 500
lr_cls: 1e-2
w_decay_cls: 0
hidden_dim_cls: 256
dropout_cls: 0.5
dropedge_cls: 0.25
n_layers_cls: 3
patience_cls: 100

epochs: 1000
lr: 0.001
wd: 0.0
n_hidden: 256
n_embed: 64
n_proj: 64
dropout: 0.5
dropedge_rate: 0.25
n_layers: 2
type_learner: mlp
k: 10
sim_function: cosine
activation_learner: relu
eval_freq: 200
tau: 0.9999
maskfeat_rate_learner: 0.4
maskfeat_rate_anchor: 0.4
contrast_batch_size: 2000
c: 50

training:
  patience: ~
  criterion: ~

dataset:
  feat_norm: false   # sublime does not normalize feats
  cora_split: false
  load_graph: false
  sparse: true

# analysis
analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph