model:
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 16
  dropout: 0.5
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

training:
  lr: 1e-2
  n_epochs: 100
  weight_decay: 5e-4
  patience: 50
  lr_adj: 1e-2
  inner_steps: 30
  outer_steps: 1

gsl:
  symmetric: false
  lambda_: 0.001
  alpha: 0.3
  beta: 2.5
  gamma: 1

dataset:
  re_split: false # for cora,citeseer and pubmed

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: true
