model:
  n_hidden: 64
  dropout: 0.5
  dprate: 0.5
  K: 10
  alpha: 0.1
  init: 'PPR'

training:
  lr: 2e-3
  weight_decay: 5e-4
  n_epochs: 1000
  patience: ~
  criterion: metric

dataset:
  feat_norm: true
  cora_split: false
  normalize: false
  add_loop: false
  sparse: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: false
  load_graph_path: results/graph/sublime