enhancedgcn: true

lr: 3e-5
n_epochs: 1000
weight_decay: 0

n_hidden: 512
n_layers: 5
dropout: 0.2
input_dropout: 0.2  # cora:0.8,citeseer:0.0
norm: true
re_split: true

# use wandb to tune hyperparams
sweep: true
sweep_config:
  method: grid
  name: gcn_enhance
  description:
  metric:
    goal: maximize
    name: val_acc
  parameters:
    batch_size:
      values: [16,32,64]
    lr:
      min: 0.0001
      max: 0.1
    epochs:
      values: [5, 10, 15]
