model:
  type: gcn
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: F.relu # [relu, elu, gelu, leakyrelu]
  n_hidden: 30
  dropout: 0.4
  input_dropout: 0
  norm:
    flag: false
    norm_type: BatchNorm1d # [LayerNorm, BatchNorm1d]
  input_layer: false
  output_layer: false
  spmm_type: 1 # specilized for sparse mltiply [0,1], expected to remove in future versions
  n_hidden_graph: 70

dataset:
  cora_split: false # for cora,citeseer and pubmed
  feat_norm: true
  normalize: true
  add_loop: true
  sparse: true
#  homophily_control: 0.8

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 5e-3
  n_epochs: 5000
  weight_decay: 1e-4
  patience: 100
  criterion: metric
  loss_lamb1: 1e-2
  loss_lamb2: 0.0001

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: false
  load_graph_path: results/graph/gen