training:
  lr: 1e-1
  weight_decay: 5e-7
  max_iter: 10
  max_epochs: 500
  patience: 100
  smoothness_ratio: 0
  degree_ratio: 0.03
  sparsity_ratio: 0

model:
  n_layers: 2
  n_hidden: 128
  dropout: 0
  norm: false
  scalable_run: true
  num_anchors: 700


gsl:
  graph_skip_conn: 0.7
  update_adj_ratio: 0.3
  graph_include_self: False

  graph_learn_epsilon: 0.1
  graph_learn_epsilon2: 0.1
  graph_learn_topk: null
  graph_learn_topk2: null
  graph_learn_num_pers: 6

  feat_adj_dropout: 0
  gl_dropout: 0

  eps_adj: 8e-5
  test_eps_adj: 8e-5

dataset:
  cora_split: false
  feat_norm: false
  sparse: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false