# data
re_split: false

# Training
lr: 0.01
weight_decay: 0
max_iter: 2
eps_adj: 1e-1
test_eps_adj: 1e-1
max_epochs: 10000
patience: 50

# Regularization
dropout: 0.3
feat_adj_dropout: 0
gl_dropout: 0

# gnn
scalable_run: true
num_anchors: 300
n_layers: 3
hidden_size: 256
batch_norm: True

# graph learning module
graph_skip_conn: 0.8
update_adj_ratio: 0.1
graph_include_self: False
smoothness_ratio: 0.2
degree_ratio: 0
sparsity_ratio: 0

graph_learn_epsilon: 0.9
graph_learn_epsilon2: 0.9
graph_learn_topk: null
graph_learn_topk2: null
graph_learn_num_pers: 1
