model:
  n_layers: 5
  n_linear: 2 # layers of linear per gcn layer
  act: gelu # [relu, elu, gelu, leakyrelu]
  general: concat #[concat, maxpool]
  n_hidden: 512
  dropout: 0.2
  input_dropout: 0.2
  norm:
    flag: true
    norm_type: LayerNorm # [LayerNorm, BatchNorm1d]
  input_layer: true
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

dataset:
  cora_split: true # for cora,citeseer and pubmed
  feat_norm: false
  add_loop: true
  normalize: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 3e-5
  n_epochs: 1000
  weight_decay: 0

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
