model:
  n_hidden: 64
  dropout: 0.5
  activation: 'relu'
  decoder_layer: 2
  decoder_n_hidden: 64

  nce_k: 16382
  nce_t: 0.07

refine_graph:
  rm_ratio: 0.05
  add_ratio: 0
  cos_batch_size: 10000
  fsim_weight: 0.1
  fsim_norm: True


dataset:
  feat_norm: true
  cora_split: false # for cora,citeseer and pubmed
  sparse: true

deepwalk:
  num_walks: 12
  window_size: 11
  walk_length: 100
  n_hidden: 64
  num_workers: 32

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-3
  weight_decay: 5e-4

  n_epochs: 1000
    
  gsr_lr: 1e-2
  gsr_weight_decay: 5e-4
  gsr_epochs: 3

  intra_weight: 0.75
  momentum_factor: 0.999

  gsl_batch_size: 128
  fan_out: '15_30'

analysis:
  flag: false
  project: gsl

search_par: true