model:
  n_hidden: 64
  dropout: 0.5
  dprate: 0.5
  K: 10
  alpha: 0.5
  init: 'PPR'

training:
  lr: 5e-2
  weight_decay: 0
  n_epochs: 1000

dataset:
  feat_norm: true
  cora_split: false
  load_graph: false
  normalize: true
  add_loop: true

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false