model:
  n_hidden: 128
  dropout: 0.2
  K: 2
  alpha: 0.3

training:
  lr: 1e-2
  weight_decay: 5e-6
  n_epochs: 1000
  patience: 100
  criterion: either

dataset:
  feat_norm: false
  cora_split: false
  normalize: true
  add_loop: true
  sparse: true
#  homophily_control: 0.8

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  load_graph: false
  load_graph_path: results/graph/idgl
  sweep: false
  sweep_id: yotsugi/gsl-benchmark/dykw00ac
  count: 500