model:
  n_hidden: 128
  n_layers: 1
  mlp_layers: 1

training:
  lr: 1e-1
  weight_decay: 5e-4
  n_epochs: 100
  patience: ~
  criterion: ~

dataset:
  feat_norm: true
  sparse: true

analysis:
  flag: false
  project: gsl
  save_graph: false