model:
  n_layers: 4
  act: relu
  n_hidden: 128
  n_heads: 2
  dropout: 0.
  use_bn: false
  M: 30
  use_gumbel: true
  use_residual: false
  use_act: false
  use_jk: false
  K: 20
  rb_order: 3
  rb_trans: sigmoid
  tau: 0.25


dataset:
  feat_norm: false
  cora_split: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 1000
  weight_decay: 0
  lambda: 1.0

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  sweep: false
  sweep_id: yotsugi/gsl-benchmark/r8n3fluk
  count: 100