model:
  n_layers: 2
  act: relu
  n_hidden: 32
  n_heads: 4
  dropout: 0.3
  use_bn: true
  M: 30
  use_gumbel: true
  use_residual: true
  use_act: false
  use_jk: false
  K: 10
  rb_order: 2
  rb_trans: sigmoid
  tau: 0.25


dataset:
  feat_norm: true
  cora_split: false
  load_graph: false

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-3
  n_epochs: 300
  weight_decay: 5e-4
  lambda: 1.0

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false