model:
  n_layers: 5
  act: relu
  n_hidden: 128
  n_heads: 1
  dropout: 0.8
  use_bn: true
  M: 30
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: false
  K: 5
  rb_order: 1
  rb_trans: sigmoid
  tau: 0.25


dataset:
  feat_norm: false
  cora_split: false
  load_graph: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-3
  n_epochs: 1000
  weight_decay: 5e-6
  lambda: 0.01
  patience: ~
  criterion: ~

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  sweep: false
  sweep_id: yotsugi/gsl-benchmark/qnh9rl0x
  count: 100