model:
  n_layers: 2
  act: F.relu
  n_hidden: 64
  n_heads: 1
  dropout: 0
  use_bn: true
  M: 30
  use_gumbel: true
  use_residual: true
  use_act: false
  use_jk: false
  K: 20
  rb_order: 2
  rb_trans: sigmoid
  tau: 0.25


dataset:
  feat_norm: false
  cora_split: false
  load_graph: false
  sparse: true

training:
  data_cpu: false # whether data should be placed in cpu instead of gpu to save space
  lr: 1e-2
  n_epochs: 300
  weight_decay: 0
  lambda: 0.1
  patience: ~
  criterion: ~

# analysis
analysis:
  flag: false
  save_graph: false
  save_graph_path: results/graph


